apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service-deployment
  labels:
    app: analytics-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
        - name: analytics-service
          image: url-shortener/analytics-service:latest
          ports:
            - containerPort: 50053 # Example port for health checks/metrics
          env:
            - name: DATABASE_URL
              value: "postgres://postgres:mysecretpassword@postgres-service:5432/postgres"
            - name: KAFKA_BROKER
              value: "kafka-service:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
spec:
  selector:
    app: analytics-service
  ports:
    - protocol: TCP
      port: 50053
      targetPort: 50053
  type: ClusterIP
