// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0
// source: shortener.proto

package shortenerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShortenURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LongUrl       string                 `protobuf:"bytes,1,opt,name=long_url,json=longUrl,proto3" json:"long_url,omitempty"`
	CustomAlias   string                 `protobuf:"bytes,2,opt,name=custom_alias,json=customAlias,proto3" json:"custom_alias,omitempty"` // Optional
	ExpiresAt     string                 `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`       // Optional: ISO 8601 format string
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                // Optional: For authenticated users
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenURLRequest) Reset() {
	*x = ShortenURLRequest{}
	mi := &file_shortener_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenURLRequest) ProtoMessage() {}

func (x *ShortenURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenURLRequest.ProtoReflect.Descriptor instead.
func (*ShortenURLRequest) Descriptor() ([]byte, []int) {
	return file_shortener_proto_rawDescGZIP(), []int{0}
}

func (x *ShortenURLRequest) GetLongUrl() string {
	if x != nil {
		return x.LongUrl
	}
	return ""
}

func (x *ShortenURLRequest) GetCustomAlias() string {
	if x != nil {
		return x.CustomAlias
	}
	return ""
}

func (x *ShortenURLRequest) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *ShortenURLRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ShortenURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortCode     string                 `protobuf:"bytes,1,opt,name=short_code,json=shortCode,proto3" json:"short_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenURLResponse) Reset() {
	*x = ShortenURLResponse{}
	mi := &file_shortener_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenURLResponse) ProtoMessage() {}

func (x *ShortenURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenURLResponse.ProtoReflect.Descriptor instead.
func (*ShortenURLResponse) Descriptor() ([]byte, []int) {
	return file_shortener_proto_rawDescGZIP(), []int{1}
}

func (x *ShortenURLResponse) GetShortCode() string {
	if x != nil {
		return x.ShortCode
	}
	return ""
}

type GetOriginalURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortCode     string                 `protobuf:"bytes,1,opt,name=short_code,json=shortCode,proto3" json:"short_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOriginalURLRequest) Reset() {
	*x = GetOriginalURLRequest{}
	mi := &file_shortener_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOriginalURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOriginalURLRequest) ProtoMessage() {}

func (x *GetOriginalURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOriginalURLRequest.ProtoReflect.Descriptor instead.
func (*GetOriginalURLRequest) Descriptor() ([]byte, []int) {
	return file_shortener_proto_rawDescGZIP(), []int{2}
}

func (x *GetOriginalURLRequest) GetShortCode() string {
	if x != nil {
		return x.ShortCode
	}
	return ""
}

type GetOriginalURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LongUrl       string                 `protobuf:"bytes,1,opt,name=long_url,json=longUrl,proto3" json:"long_url,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // Optional: ISO 8601 format string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOriginalURLResponse) Reset() {
	*x = GetOriginalURLResponse{}
	mi := &file_shortener_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOriginalURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOriginalURLResponse) ProtoMessage() {}

func (x *GetOriginalURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOriginalURLResponse.ProtoReflect.Descriptor instead.
func (*GetOriginalURLResponse) Descriptor() ([]byte, []int) {
	return file_shortener_proto_rawDescGZIP(), []int{3}
}

func (x *GetOriginalURLResponse) GetLongUrl() string {
	if x != nil {
		return x.LongUrl
	}
	return ""
}

func (x *GetOriginalURLResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

type UpdateURLDestinationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortCode     string                 `protobuf:"bytes,1,opt,name=short_code,json=shortCode,proto3" json:"short_code,omitempty"`
	NewLongUrl    string                 `protobuf:"bytes,2,opt,name=new_long_url,json=newLongUrl,proto3" json:"new_long_url,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // For authorization check
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateURLDestinationRequest) Reset() {
	*x = UpdateURLDestinationRequest{}
	mi := &file_shortener_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateURLDestinationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateURLDestinationRequest) ProtoMessage() {}

func (x *UpdateURLDestinationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateURLDestinationRequest.ProtoReflect.Descriptor instead.
func (*UpdateURLDestinationRequest) Descriptor() ([]byte, []int) {
	return file_shortener_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateURLDestinationRequest) GetShortCode() string {
	if x != nil {
		return x.ShortCode
	}
	return ""
}

func (x *UpdateURLDestinationRequest) GetNewLongUrl() string {
	if x != nil {
		return x.NewLongUrl
	}
	return ""
}

func (x *UpdateURLDestinationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UpdateURLDestinationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortCode     string                 `protobuf:"bytes,1,opt,name=short_code,json=shortCode,proto3" json:"short_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateURLDestinationResponse) Reset() {
	*x = UpdateURLDestinationResponse{}
	mi := &file_shortener_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateURLDestinationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateURLDestinationResponse) ProtoMessage() {}

func (x *UpdateURLDestinationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateURLDestinationResponse.ProtoReflect.Descriptor instead.
func (*UpdateURLDestinationResponse) Descriptor() ([]byte, []int) {
	return file_shortener_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateURLDestinationResponse) GetShortCode() string {
	if x != nil {
		return x.ShortCode
	}
	return ""
}

func (x *UpdateURLDestinationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_shortener_proto protoreflect.FileDescriptor

const file_shortener_proto_rawDesc = "" +
	"\n" +
	"\x0fshortener.proto\x12\tshortener\"\x89\x01\n" +
	"\x11ShortenURLRequest\x12\x19\n" +
	"\blong_url\x18\x01 \x01(\tR\alongUrl\x12!\n" +
	"\fcustom_alias\x18\x02 \x01(\tR\vcustomAlias\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\tR\texpiresAt\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\"3\n" +
	"\x12ShortenURLResponse\x12\x1d\n" +
	"\n" +
	"short_code\x18\x01 \x01(\tR\tshortCode\"6\n" +
	"\x15GetOriginalURLRequest\x12\x1d\n" +
	"\n" +
	"short_code\x18\x01 \x01(\tR\tshortCode\"R\n" +
	"\x16GetOriginalURLResponse\x12\x19\n" +
	"\blong_url\x18\x01 \x01(\tR\alongUrl\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\tR\texpiresAt\"w\n" +
	"\x1bUpdateURLDestinationRequest\x12\x1d\n" +
	"\n" +
	"short_code\x18\x01 \x01(\tR\tshortCode\x12 \n" +
	"\fnew_long_url\x18\x02 \x01(\tR\n" +
	"newLongUrl\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"W\n" +
	"\x1cUpdateURLDestinationResponse\x12\x1d\n" +
	"\n" +
	"short_code\x18\x01 \x01(\tR\tshortCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x9d\x02\n" +
	"\x10ShortenerService\x12I\n" +
	"\n" +
	"ShortenURL\x12\x1c.shortener.ShortenURLRequest\x1a\x1d.shortener.ShortenURLResponse\x12U\n" +
	"\x0eGetOriginalURL\x12 .shortener.GetOriginalURLRequest\x1a!.shortener.GetOriginalURLResponse\x12g\n" +
	"\x14UpdateURLDestination\x12&.shortener.UpdateURLDestinationRequest\x1a'.shortener.UpdateURLDestinationResponseBFZDgithub.com/Farhang-Osman/url-shortener-project/pkg/proto/shortenerpbb\x06proto3"

var (
	file_shortener_proto_rawDescOnce sync.Once
	file_shortener_proto_rawDescData []byte
)

func file_shortener_proto_rawDescGZIP() []byte {
	file_shortener_proto_rawDescOnce.Do(func() {
		file_shortener_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shortener_proto_rawDesc), len(file_shortener_proto_rawDesc)))
	})
	return file_shortener_proto_rawDescData
}

var file_shortener_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_shortener_proto_goTypes = []any{
	(*ShortenURLRequest)(nil),            // 0: shortener.ShortenURLRequest
	(*ShortenURLResponse)(nil),           // 1: shortener.ShortenURLResponse
	(*GetOriginalURLRequest)(nil),        // 2: shortener.GetOriginalURLRequest
	(*GetOriginalURLResponse)(nil),       // 3: shortener.GetOriginalURLResponse
	(*UpdateURLDestinationRequest)(nil),  // 4: shortener.UpdateURLDestinationRequest
	(*UpdateURLDestinationResponse)(nil), // 5: shortener.UpdateURLDestinationResponse
}
var file_shortener_proto_depIdxs = []int32{
	0, // 0: shortener.ShortenerService.ShortenURL:input_type -> shortener.ShortenURLRequest
	2, // 1: shortener.ShortenerService.GetOriginalURL:input_type -> shortener.GetOriginalURLRequest
	4, // 2: shortener.ShortenerService.UpdateURLDestination:input_type -> shortener.UpdateURLDestinationRequest
	1, // 3: shortener.ShortenerService.ShortenURL:output_type -> shortener.ShortenURLResponse
	3, // 4: shortener.ShortenerService.GetOriginalURL:output_type -> shortener.GetOriginalURLResponse
	5, // 5: shortener.ShortenerService.UpdateURLDestination:output_type -> shortener.UpdateURLDestinationResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shortener_proto_init() }
func file_shortener_proto_init() {
	if File_shortener_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shortener_proto_rawDesc), len(file_shortener_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shortener_proto_goTypes,
		DependencyIndexes: file_shortener_proto_depIdxs,
		MessageInfos:      file_shortener_proto_msgTypes,
	}.Build()
	File_shortener_proto = out.File
	file_shortener_proto_goTypes = nil
	file_shortener_proto_depIdxs = nil
}
