syntax = "proto3";

package shortener;

option go_package = "github.com/Farhang-Osman/url-shortener-project/pkg/proto/shortenerpb";

service ShortenerService {
  rpc ShortenURL (ShortenURLRequest) returns (ShortenURLResponse);
  rpc GetOriginalURL (GetOriginalURLRequest) returns (GetOriginalURLResponse);
  rpc UpdateURLDestination (UpdateURLDestinationRequest) returns (UpdateURLDestinationResponse);
  rpc GetURLAnalytics (GetURLAnalyticsRequest) returns (GetURLAnalyticsResponse);
  rpc GetTotalClicks (GetTotalClicksRequest) returns (GetTotalClicksResponse);
}

message ShortenURLRequest {
  string long_url = 1;
  string custom_alias = 2; // Optional
  string expires_at = 3; // Optional: ISO 8601 format string
  string user_id = 4; // Optional: For authenticated users
}

message ShortenURLResponse {
  string short_code = 1;
}

message GetOriginalURLRequest {
  string short_code = 1;
}

message GetOriginalURLResponse {
  string long_url = 1;
  string expires_at = 2; // Optional: ISO 8601 format string
}

message UpdateURLDestinationRequest {
  string short_code = 1;
  string new_long_url = 2;
  string user_id = 3; // For authorization check
}

message UpdateURLDestinationResponse {
  string short_code = 1;
  string message = 2;
}

message GetURLAnalyticsRequest {
  string short_code = 1;
  string user_id = 2;
}

message GetURLAnalyticsResponse {
  string event_type = 1;
  string short_code = 2;
  string long_url = 3; // Only for url_created events
  string user_id = 4; // Only for url_created events
  string user_agent = 5; // Only for url_clicked events
  string referer = 6; // Only for url_clicked events
  string ip_address = 7;
  string timestamp = 8; // ISO 8601 format string
}

message GetTotalClicksRequest {
  string short_code = 1;
  string user_id = 2; // For authorization check
}

message GetTotalClicksResponse {
  int64 total_clicks = 1;
}